command-names:
  create: loo
  remove: kustuta
  move: liiguta
  addowner: lisaomanik
  addmember: lisaliige
  removeowner: eemaldaomanik
  removemember: eemaldaliige
  reload: taaslae
  info: info
  stats: statistika

permissions:
  admin: "hiiela.staff"

messages:
  no_permission: "<red>Nii ei saa teha :C"
  player_only: "<red>Seda saab kasutada ainult mängija."
  invalid_args: "<red>Valed või ebasobilikus koguses argumendid."
  region_created: "<green>Lõid ala <yellow>%region_name%</yellow> mängijale <yellow>%player_name%</yellow>!</green>"
  region_overlap: "<red>See ala on mingi teise ala sees!</red>"
  no_selection: "<red>Pead kõigepealt WorldEditiga ala määrama.</red>"
  region_removed: "<green>Kustutasid ala <yellow>%region_name%</yellow>!</green>"
  region_not_found: "<red>Täpsustatud ala ei leitud!</red>"
  region_not_here: "<red>Siit kus sa seisad, ei leitud ala!</red>"
  region_moved: "<green>Liigutasid ala <yellow>%region_name%</yellow> uuele kohale!</green>"
  owner_added: "<green>Lisasid mängija <yellow>%player_name%</yellow> omanikuna alale <yellow>%region_name%</yellow>!</green>"
  member_added: "<green>Lisasid mängija <yellow>%player_name%</yellow> liikmena alale <yellow>%region_name%</yellow>!</green>"
  owner_removed: "<green>Eemaldasid mängija <yellow>%player_name%</yellow> omaniku rollist alalt <yellow>%region_name%</yellow>!</green>"
  member_removed: "<green>Eemaldasid mängija <yellow>%player_name%</yellow> liikme rollist alalt <yellow>%region_name%</yellow>!</green>"
  not_owner: "<red>Sa ei ole selle ala omanik!</red>"
  staff_help_message: "<gold>--- Kaitsed ---</gold><br> <br><gray>Noolsulgudes (<>) argumendid on vajalikud. Kastsulgudes ([]) argumendid on valikulised.<br><gray>Kui on mitu argumenti samades sulgudes eraldatud postiga (|), siis tuleb sisestada ainult üks antud valikutest.<br><gray>Regiooni (alade) nimede ette käib #. Kui tahad kasutada kasutada ala, kus praegu seisad, siis võid kasutada @here argumendina (kui võimalik).<br><gray>Ala numbriks tahetakse ainult numbrit (mitmes ala).<br><yellow>/kaitse loo <mängija> [no]</yellow> <gray>- Ilma viimase argumendita loob ala vertikaalselt pikendatuna (expand vert). [no] argument määrab, et soovid kindlates määratud mõõtmetes ala.<br><yellow>/kaitse kustuta <mängija|#regioon|@here> <gray>- Kui argumendiks on mängija, kustutab see mängija viimasena lisatud ala.</yellow><br><yellow>/kaitse liiguta <mängija|#regioon> [no] <gray>- Kui esimeseks argumendiks on mängija, liigutab see mängija viimasena lisatud ala. Ilma viimase argumendita liigutab see ala vertikaalselt pikendatuna (expand vert). [no] argument määrab, et soovid kindlates määratud mõõtmetes ala.</yellow><br><yellow>/kaitse lisaomanik <mängija> [#regioon|ala number] <gray>- Kui viimast argumenti ei ole, lisab see mängija sellele alale, kus seisad.</yellow><br><yellow>/kaitse eemaldaomanik <mängija> [#regioon|ala number] <gray>- Kui viimast argumenti ei ole, eemaldab see mängija sellelt alalt, kus seisad.</yellow><br><yellow>/kaitse lisaliige <mängija> [#regioon|ala number] <gray>- Kui viimast argumenti ei ole, lisab see mängija sellele alale, kus seisad.</yellow><br><yellow>/kaitse eemaldaliige <mängija> [#regioon|ala number] <gray>- Kui viimast argumenti ei ole, eemaldab see mängija sellelt alalt, kus seisad.</yellow><br><yellow>/kaitse taaslae</yellow><br><yellow>/kaitse statistika</yellow><br><yellow>/kaitse info [mängija] <gray>- Kui viimast argumenti ei ole, näitab sinu enda infot.</yellow>"
  player_help_message: "<gold>--- Kaitsed ---</gold><br> <br><gray>Noolsulgudes (<>) argumendid on vajalikud. Kastsulgudes ([]) argumendid on valikulised.<br><gray>Kui on mitu argumenti samades sulgudes eraldatud postiga (|), siis tuleb sisestada ainult üks antud valikutest.<br><gray>Regiooni (alade) nimede ette käib #.<br><gray>Ala numbriks tahetakse ainult numbrit (mitmes ala).<br><yellow>/kaitse lisaomanik <mängija> [#regioon|ala number] <gray>- Kui viimast argumenti ei ole, lisab see mängija sellele alale, kus seisad.</yellow><br><yellow>/kaitse eemaldaomanik <mängija> [#regioon|ala number] <gray>- Kui viimast argumenti ei ole, eemaldab see mängija sellelt alalt, kus seisad.</yellow><br><yellow>/kaitse lisaliige <mängija> [#regioon|ala number] <gray>- Kui viimast argumenti ei ole, lisab see mängija sellele alale, kus seisad.</yellow><br><yellow>/kaitse eemaldaliige <mängija> [#regioon|ala number] <gray>- Kui viimast argumenti ei ole, eemaldab see mängija sellelt alalt, kus seisad.<br><yellow>/kaitse info [mängija] <gray>- Kui viimast argumenti ei ole, näitab sinu enda infot.</yellow>"
  usage_create: "<red>Kasutus: /kaitse loo <mängija> [no] <gray><- viimane määrab, kas ala peaks olema vertikaalselt pikendatud. Tavaliselt jah.</gray></red>"
  usage_remove: "<red>Kasutus: /kaitse kustuta <mängija|#regioon|@here></red>"
  usage_move: "<red>Kasutus: /kaitse liiguta <mängija|#regioon> [no] <gray><- viimane määrab, kas ala peaks olema vertikaalselt pikendatud. Tavaliselt jah.</gray></red>"
  usage_addowner: "<red>Kasutus: /kaitse lisaomanik <mängija> [#regioon|ala number]</red>"
  usage_removeowner: "<red>Kasutus: /kaitse eemaldaomanik <mängija> [#regioon|ala number]</red>"
  usage_addmember: "<red>Kasutus: /kaitse lisaliige <mängija> [#regioon|ala number]</red>"
  usage_removemember: "<red>Kasutus: /kaitse eemaldaliige <mängija> [#regioon|ala number]</red>"
  cannot_remove_yourself: "<red>Iseennast ei saa alalt eemaldada!"
  target_already_added: "<red>See mängija on juba alale lisatud!"
  target_not_added: "<red>Seda mängijat ei ole alale lisatud!"
  plugin_reloaded: "<green>Konfiguratsioon taaslaetud!</green>"
  info_message: "<gray>Mängijal <green>%target_player%</green> on <green>%regions%</green> regiooni: %entries%</gray>"
  info_entry: "<br><gray>- <green>%region_name%"
  info_none: "<gray>Mängijal <green>%target_player%</green> ei ole ühtegi regiooni."
  stats_message: "<gray>Sinu loodud regioonid: <green>%count%</green><br><gray>TOP 3 parimat: %entries%"
  stats_entry: "<br><gold>%rank%.</gold> <green>%creator_name%</green> <gray>-</gray> <green>%count%</green> <gray>regiooni.</gray>"
  stats_missing: "<br><gold>%rank%.</gold> <gray>Andmed puuduvad...</gray>"

commands_before_create: []

commands_on_create:
  - "execute as %command_runner% run rg flag -w %world% %region_name% greeting Sisenesid %region_name% alale."
  - "execute as %command_runner% run rg flag -w %world% %region_name% farewell Lahkusid %region_name% alalt."
